### ISSUE TITLE
Volume servers don't notice master change

### ISSUE THREAD

**Issue by eryx67** [chrislusf/seaweedfs#1414] opened 2020-08-06 08:56 UTC
We have a constant bug in low load cluster when volume servers don't notice master change.

**Our setup**

SeaweedFS version - we tryed 1.56 and 1.87

Three hosts 192.168.50.{71,72,73}.
There are one master on port 9333 and three volume servers on ports 8081, 8082 8083 per host.
All volume servers are in the same DC but are formed in three racks, one rack per host.

Commands to start are identical on every host:
```
/bin/weed -v 0 volume -index=leveldbMedium -dataCenter=dc1 -rack=rack1 -dir=/data/swfs/volume1 -max=300 -ip=192.168.50.71 -port=8081 -port.public=8181 -publicUrl=http://192.168.50.71:8181 -mserver=192.168.50.71:9333,192.168.50.72:9333,192.168.50.73:9333
/bin/weed -v 0 volume -index=leveldbMedium -dataCenter=dc1 -rack=rack1 -dir=/data/swfs/volume3 -max=300 -ip=192.168.50.71 -port=8083 -port.public=8183 -publicUrl=http://192.168.50.71:8183 -mserver=192.168.50.71:9333,192.168.50.72:9333,192.168.50.73:9333
/bin/weed -v 0 volume -index=leveldbMedium -dataCenter=dc1 -rack=rack1 -dir=/data/swfs/volume2 -max=300 -ip=192.168.50.71 -port=8082 -port.public=8182 -publicUrl=http://192.168.50.71:8182 -mserver=192.168.50.71:9333,192.168.50.72:9333,192.168.50.73:9333

/bin/weed -v 0 master -volumeSizeLimitMB=50 -defaultReplication=011 -mdir=/data/swfs/master -ip=192.168.50.71 -port=9333 -peers=192.168.50.71:9333,192.168.50.72:9333,192.168.50.73:9333

```

**Problem**

When master changed all volume servers sometimes don't notice new master and keep connection with old one.
As a result new master know nothing about volume servers.

Cluster status:
```
{
  "Leader": "192.168.50.73:9333",
  "Peers": [
    "192.168.50.73:9333",
    "192.168.50.72:9333"
  ]
}
```

Log from master where we can see new master election:
```
I0806 00:58:45 24607 master_server.go:142] event: &{typ:leaderChange source:0xc0001fa360 value: prevValue:192.168.50.72:9333}
I0806 00:58:46 24607 master_server.go:148] state change: &{typ:stateChange source:0xc0001fa360 value:leader prevValue:candidate}
I0806 00:58:46 24607 master_server.go:142] event: &{typ:leaderChange source:0xc0001fa360 value:192.168.50.71:9333 prevValue:}
I0806 00:58:46 24607 master_server.go:144] [ 192.168.50.71:9333 ] 192.168.50.71:9333 becomes leader.
I0806 01:02:16 24607 master_server.go:148] state change: &{typ:stateChange source:0xc0001fa360 value:follower prevValue:leader}
I0806 01:02:20 24607 master_server.go:142] event: &{typ:leaderChange source:0xc0001fa360 value:192.168.50.73:9333 prevValue:}
I0806 01:02:20 24607 master_server.go:144] [ 192.168.50.71:9333 ] 192.168.50.73:9333 becomes leader.
I0806 01:03:48 24607 master_server.go:142] event: &{typ:leaderChange source:0xc0001fa360 value: prevValue:192.168.50.73:9333}
I0806 01:03:48 24607 master_server.go:142] event: &{typ:leaderChange source:0xc0001fa360 value:192.168.50.73:9333 prevValue:}
I0806 01:03:48 24607 master_server.go:144] [ 192.168.50.71:9333 ] 192.168.50.73:9333 becomes leader.

```

Connections list on the host of old master:
```
ESTAB      0      0      192.168.50.71:60000              192.168.50.71:19333               users:(("weed",pid=24607,fd=14))
ESTAB      0      0      192.168.50.71:39154              192.168.50.73:18081               users:(("weed",pid=24607,fd=42))
ESTAB      0      0      192.168.50.71:36896              192.168.50.73:19333               users:(("weed",pid=24607,fd=22))
ESTAB      0      0      192.168.50.71:41148              192.168.50.71:19333               users:(("weed",pid=24265,fd=66))
ESTAB      0      0      192.168.50.71:47516              192.168.50.71:18081               users:(("weed",pid=24607,fd=43))
ESTAB      0      0      192.168.50.71:44232              192.168.50.72:19333               users:(("weed",pid=24607,fd=20))
ESTAB      0      0      192.168.50.71:54940              192.168.50.72:18082               users:(("weed",pid=24607,fd=38))
ESTAB      0      0      192.168.50.71:41146              192.168.50.71:19333               users:(("weed",pid=24264,fd=34))
ESTAB      0      0      192.168.50.71:44190              192.168.50.72:19333               users:(("weed",pid=24607,fd=13))
ESTAB      0      0      192.168.50.71:39816              192.168.50.72:9333                users:(("weed",pid=24607,fd=923))
ESTAB      0      0      192.168.50.71:36858              192.168.50.73:19333               users:(("weed",pid=24607,fd=18))
ESTAB      0      0      192.168.50.71:36884              192.168.50.73:19333               users:(("weed",pid=24607,fd=21))
ESTAB      0      0      192.168.50.71:60398              192.168.50.71:9333                users:(("weed",pid=24262,fd=58))
ESTAB      0      0      192.168.50.71:50170              192.168.50.72:18081               users:(("weed",pid=24607,fd=35))
ESTAB      0      0      192.168.50.71:48738              192.168.50.73:19333               users:(("weed",pid=24607,fd=24))
ESTAB      0      0      192.168.50.71:41150              192.168.50.71:19333               users:(("weed",pid=24262,fd=41))
ESTAB      0      0      192.168.50.71:44188              192.168.50.72:19333               users:(("weed",pid=24607,fd=16))
ESTAB      0      0      192.168.50.71:33368              192.168.50.73:18082               users:(("weed",pid=24607,fd=41))
ESTAB      0      0      192.168.50.71:48946              192.168.50.71:18082               users:(("weed",pid=24607,fd=36))
ESTAB      0      0      192.168.50.71:50564              192.168.50.73:18083               users:(("weed",pid=24607,fd=40))
ESTAB      0      0      192.168.50.71:50906              192.168.50.72:18083               users:(("weed",pid=24607,fd=39))
ESTAB      0      0      192.168.50.71:33506              192.168.50.73:9333                users:(("weed",pid=24607,fd=26))
ESTAB      0      0      192.168.50.71:54044              192.168.50.71:18083               users:(("weed",pid=24607,fd=37))
ESTAB      0      0      192.168.50.71:35770              192.168.50.73:9333                users:(("weed",pid=24607,fd=931))
ESTAB      0      0      192.168.50.71:36860              192.168.50.73:19333               users:(("weed",pid=24607,fd=19))
ESTAB      0      0       [::ffff:192.168.50.71]:19333               [::ffff:192.168.50.73]:40678               users:(("weed",pid=24607,fd=17))
ESTAB      0      0       [::ffff:192.168.50.71]:19333               [::ffff:192.168.50.73]:49992               users:(("weed",pid=24607,fd=28))
ESTAB      0      0       [::ffff:192.168.50.71]:9333                [::ffff:192.168.50.71]:60398               users:(("weed",pid=24607,fd=51))
ESTAB      0      0       [::ffff:192.168.50.71]:18082               [::ffff:192.168.50.71]:48946               users:(("weed",pid=24265,fd=67))
ESTAB      0      0       [::ffff:192.168.50.71]:18081               [::ffff:192.168.50.73]:49072               users:(("weed",pid=24262,fd=44))
ESTAB      0      0       [::ffff:192.168.50.71]:19333               [::ffff:192.168.50.73]:52480               users:(("weed",pid=24607,fd=46))
ESTAB      0      0       [::ffff:192.168.50.71]:9333                [::ffff:192.168.50.73]:52468               users:(("weed",pid=24607,fd=58))
ESTAB      0      0       [::ffff:192.168.50.71]:19333               [::ffff:192.168.50.72]:42828               users:(("weed",pid=24607,fd=31))
ESTAB      0      0       [::ffff:192.168.50.71]:9333                [::ffff:192.168.50.72]:37546               users:(("weed",pid=24607,fd=33))
ESTAB      0      0       [::ffff:192.168.50.71]:19333               [::ffff:192.168.50.71]:41148               users:(("weed",pid=24607,fd=48))
ESTAB      0      0       [::ffff:192.168.50.71]:18083               [::ffff:192.168.50.71]:54044               users:(("weed",pid=24264,fd=37))
ESTAB      0      0       [::ffff:192.168.50.71]:19333               [::ffff:192.168.50.72]:42830               users:(("weed",pid=24607,fd=32))
ESTAB      0      0       [::ffff:192.168.50.71]:9333                [::ffff:192.168.50.73]:43658               users:(("weed",pid=24607,fd=34))
ESTAB      0      0       [::ffff:192.168.50.71]:9333                [::ffff:192.168.50.73]:59592               users:(("weed",pid=24607,fd=27))
ESTAB      0      0       [::ffff:192.168.50.71]:9333                [::ffff:192.168.50.72]:46924               users:(("weed",pid=24607,fd=44))
ESTAB      0      0       [::ffff:192.168.50.71]:18083               [::ffff:192.168.50.73]:38330               users:(("weed",pid=24264,fd=38))
ESTAB      0      0       [::ffff:192.168.50.71]:19333               [::ffff:192.168.50.72]:33472               users:(("weed",pid=24607,fd=11))
ESTAB      0      0       [::ffff:192.168.50.71]:19333               [::ffff:192.168.50.72]:42826               users:(("weed",pid=24607,fd=30))
ESTAB      0      0       [::ffff:192.168.50.71]:18082               [::ffff:192.168.50.73]:42020               users:(("weed",pid=24265,fd=68))
ESTAB      0      0       [::ffff:192.168.50.71]:19333               [::ffff:192.168.50.73]:49994               users:(("weed",pid=24607,fd=29))
ESTAB      0      0       [::ffff:192.168.50.71]:19333               [::ffff:192.168.50.73]:49990               users:(("weed",pid=24607,fd=25))
ESTAB      0      0       [::ffff:192.168.50.71]:19333               [::ffff:192.168.50.71]:60000               users:(("weed",pid=24607,fd=15))
ESTAB      0      0       [::ffff:192.168.50.71]:18081               [::ffff:192.168.50.71]:47516               users:(("weed",pid=24262,fd=43))
ESTAB      0      0       [::ffff:192.168.50.71]:19333               [::ffff:192.168.50.71]:41146               users:(("weed",pid=24607,fd=47))
ESTAB      0      0       [::ffff:192.168.50.71]:19333               [::ffff:192.168.50.71]:41150               users:(("weed",pid=24607,fd=49))
ESTAB      0      0       [::ffff:192.168.50.71]:19333               [::ffff:192.168.50.72]:45288               users:(("weed",pid=24607,fd=45))
```

**Comment by chrislusf** [comment] 2020-08-06 09:56
why the volume servers have the same `-ip=192.168.50.71` ?

**Comment by eryx67** [comment] 2020-08-06 10:14
> why the volume servers have the same `-ip=192.168.50.71` ?

we use one volume server per physical disk and replication mode '011',
we don't have a need to place every volume server in the rack to distinct IP.

**Comment by chrislusf** [comment] 2020-08-06 11:03
do you have the logs on the volume servers at the same time?

**Comment by eryx67** [comment] 2020-08-06 11:27
> do you have the logs on the volume servers at that same time?

Yes, but all logs for all volumes servers last messages are far earlier, for example:
```
I0804 11:16:38 24264 volume_grpc_client_to_master.go:74] Heartbeat to: 192.168.50.73:9333
I0804 11:16:43 24264 volume_grpc_client_to_master.go:95] Volume Server found a new master newLeader: 192.168.50.71:9333 instead of 192.168.50.73:9333
I0804 11:16:46 24264 volume_grpc_client_to_master.go:74] Heartbeat to: 192.168.50.71:9333
I0805 00:40:47 24264 volume_grpc_client_to_master.go:95] Volume Server found a new master newLeader: 192.168.50.73:9333 instead of 192.168.50.71:9333
I0805 00:40:50 24264 volume_grpc_client_to_master.go:74] Heartbeat to: 192.168.50.73:9333
I0805 01:01:16 24264 volume_grpc_client_to_master.go:95] Volume Server found a new master newLeader: 192.168.50.71:9333 instead of 192.168.50.73:9333
I0805 01:01:19 24264 volume_grpc_client_to_master.go:74] Heartbeat to: 192.168.50.71:9333
I0805 12:40:01 24264 store.go:119] In dir /data/swfs/volume3 adds volume:95 collection:MAIL_20200805_TTL15d replicaPlacement:011 ttl:15d
I0805 12:40:01 24264 volume_loading.go:119] loading leveldb medium /data/swfs/volume3/MAIL_20200805_TTL15d_95.ldb
I0805 12:40:01 24264 store.go:123] add volume 95
```

Also I have to mention the following.
At the time of failure the master was `192.168.50.73` and when I had restarted the previous master `192.168.50.71`
I got in logs:
```
I0806 11:58:15 24264 volume_grpc_client_to_master.go:180] Volume Server Failed to talk with master 192.168.50.71:9333: EOF
I0806 11:58:15 24264 volume_grpc_client_to_master.go:51] heartbeat error: EOF
I0806 11:58:20 24264 volume_grpc_client_to_master.go:74] Heartbeat to: 192.168.50.71:9333
I0806 11:58:21 24264 volume_grpc_client_to_master.go:95] Volume Server found a new master newLeader: 192.168.50.73:9333 instead of 192.168.50.71:9333
I0806 11:58:24 24264 volume_grpc_client_to_master.go:74] Heartbeat to: 192.168.50.73:9333

```

and cluster returned to normal state.

**Comment by chrislusf** [comment] 2020-08-06 16:42
Is this easily reproducible? I made some change, but still not sure about the fix.

**Comment by eryx67** [comment] 2020-08-07 03:49
> Is this easily reproducible? I made some change, but still not sure about the fix.

Unfortunately I can't reproduce it by hands.
I tried to kill master to master connections leaving volume server to master
unaffected to provoke leader changing but masters just reconnected.

**Comment by chrislusf** [comment] 2020-08-11 03:50
closing this since no actionable items. Will keep an eye possible related issues.

**Closed by chrislusf** 2020-08-11 03:50 UTC
