### ISSUE TITLE
master got a panic

### ISSUE THREAD

**Issue by mschneider82** [chrislusf/seaweedfs#1912] opened 2021-03-16 10:17 UTC
**Describe the bug**
panic (version /2.33/linux_amd64.tar.gz)

**System Setup**
3 seaweeds with this command:
```weed server -master.port=9333 -volume.port=8080 -dir="/data/seaweedfs" -master.defaultReplication=001 -ip=10.1.3.11 -master.peers=10.1.3.13:9333,10.1.3.12:9333,10.1.3.11:9333```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x18d67a6]

goroutine 184 [running]:
github.com/chrislusf/seaweedfs/weed/topology.(*DataNode).GetDataCenter(0xc00074f5e0, 0xc00072d580)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/topology/data_node.go:180 +0x26
github.com/chrislusf/seaweedfs/weed/server.(*MasterServer).SendHeartbeat(0xc000016e00, 0x262fe98, 0xc000959000, 0x0, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/server/master_grpc_server.go:86 +0x12a5
github.com/chrislusf/seaweedfs/weed/pb/master_pb._Seaweed_SendHeartbeat_Handler(0x21af460, 0xc000016e00, 0x2628a28, 0xc0000d4240, 0x351e8e0, 0xc00086b200)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/pb/master_pb/master.pb.go:4341 +0xad
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0003daea0, 0x2632978, 0xc0007e7800, 0xc00086b200, 0xc0004b3230, 0x34c9980, 0x0, 0x0, 0x0)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1329 +0xcd8
google.golang.org/grpc.(*Server).handleStream(0xc0003daea0, 0x2632978, 0xc0007e7800, 0xc00086b200, 0x0)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1409 +0xc68
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00072c9a0, 0xc0003daea0, 0x2632978, 0xc0007e7800, 0xc00086b200)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa5
```

**Comment by chrislusf** [comment] 2021-03-16 10:25
how often does it happen?
what is the result of `volume.list`?

**Comment by mschneider82** [comment] 2021-03-16 12:14
it was one time after creating a newly 3 node cluster, on one node, i think i missed the rack / datacenter parameters. I thought that there was a default for this.

**Comment by chrislusf** [comment] 2021-03-16 18:09
They do have default values. So I am wondering how to reproduce this.

**Comment by mschneider82** [comment] 2021-03-16 19:40
Could this be caused because I have used `-master.defaultReplication=001` without using a rackname? 
Or because I have added the servers local -ip also in remote master peers. 

I think the volume list was empty at that time. I just started new nodes. Maybe I have uploaded a single file. Could not remember.  I changed my setup and added a DC and rackname, it's running fine now

**Comment by chrislusf** [comment] 2021-03-17 06:07
It is very weird that this error ever happened. I could not figure out the reason.

Closing this unless some new helpful information.

**Closed by chrislusf** 2021-03-17 06:07 UTC
