### ISSUE TITLE
Filer.sync: out of sync dir/file tree after mv command on fuse mount

### ISSUE THREAD

**Issue by KevinBLT** [chrislusf/seaweedfs#2548] opened 2022-01-01 11:57 UTC
Hello! 

First of all a big thank you ! - seaweedfs seems to be the first storage solution that fits our
needs after a lot of tries and errors using other solutions (DRBD, Ceph and GlusterFS) ! :-)

**Describe the bug**
Having a mounted filer via fuse mount and a folder name `test`.
Let this folder contain a lot of folders and files in each folder (maybe 1GB of data).
Copying the data into it was completely fine and filer.sync kept on like it was synchronous.
All nice so far!

Now an Server1: cd into mounted folder do `mv test testx` on server1 all OK
On server2/3: cd into mounted folder `testx `exists, but some files are gone?
getting them via curl shows empty data. 

Now on server1 try go back to state: `mv testx test`, looks okish.
Server1/2 also see (using `ls`) `test` but a rest of `testx` stays even after
time. Ok try do a `rm -rf testx` on server2 since it looks like dead data.

On server1 some files in `test` are missing, which was deleted via the other server removing `testx` (which should not exists).

From what I understand: Renaming doesn't do anything to the files itself and their key, so
it's clear that "the files were deleted" (from data point of view) only the directory listing
seems to be corrupted. filer.sync seems to not apply *all* changes to the file path
instead only some when doing a rename of the upper most parent.

I hope it was somewhat understandable.

**System Setup**

On three servers:
```
weed -logdir=/var/log/seaweedfs server \
  -dataCenter $HOSTNAME \
  -ip $HOSTNAME \
  -master.dir /var/.database/seaweedfs/meta \
  -dir /var/.storage \
  -volume.dir.idx /var/.database/seaweedfs/meta \
  -volume.index leveldbLarge \
  -rack 1
  -volume.disk ssd
  -filer \
```
- On Server 1: `weed filer.sync -a app1:8888 -b app2:8888 && weed filer.sync -a app1:8888 -b app3:8888`
- On Server 2: `weed filer.sync -a app2:8888 -b app1:8888 && weed filer.sync -a app2:8888 -b app3:8888`
- On Server 3:`weed filer.sync -a app3:8888 -b app1:8888 && weed filer.sync -a app3:8888 -b app2:8888`
- OS: Ubuntu 20.04.3 LTS
- Version: version 8000GB 2.83 c935b9669e6b18a07c28939b1bd839552e7d2cf5 linux amd64
- No special filer toml

**Expected behavior**
Keeping the diretories and their paths in sync.

**Screenshots**
Sorry no screenshot, look description.

**Additional context**
What can we do in this corrupted state? Copying over the other volume files? 
Do some "filer.resync" command?
*Info*: when changin/adding anther file - sync is correct. Even if I edit a file missing on Server2/3 on Server1 with vi and
save - it reappears! Seems like only the directory/file tree is corrupt on the other filers!

**One other small question**:  
For the case that filer, master and volume server is on the same server, would it be possible to create a unsix socket? Would feel safer with it and could even be a better solution performance wise! :-)

Thank you for looking at this, please ask if you need more information!

**Comment by chrislusf** [comment] 2022-01-01 20:46
The `filer.sync` process is bi-directional by default, unless `-isActivePassive` is specified.
So just one `filer.sync` process is enough between each cluster (or server in your case since each server is a cluster here).

Curious to know what are things other solutions do not have? Maybe share your thoughts on the features and disadvantages of each system you tried.

**Comment by KevinBLT** [comment] 2022-01-01 23:43
Thoughts and ideas:  

In general the servers are place at the country border and are connected via vpncloud. Replication of the databases and such is done with their own implementation (everything is active-active). 
So the last issue was the filesystem - but one info before: Everything must be active-active and 100% replicated,
so each server has the same state as one another. On Filesystem level, it's not not necessary to be be consistent within one write (so there can be a log of 100ms or what ever, not important).

For the tests: GlusterFS is working great in terms of high availability and data integrity and I could have lived with not so fast write speed but boy, that was a damn slow load time via mount. DRBD was not sure about a three node cluster and after messing around a bit and reading it was not promising to be good for active-active in that case. Ceph on the other hand looked promising but I was just not able to set it up easily unless you want your server to be spammed with a lot of docker containers. Was not so good. MooseFS was considered, but since there was not HA with Master-Master for free, was not an idea. Then we came with Seaweed and it's near native fast with fuse mount and enables async active-active replication via the filer.sync. So from that point all fine! 

I know that the filer sync is bidirectional by default, the reason I am calling it from both sides is to have one node completely failing and the other must be untouched, there was no problem with it? Could it cause trouble?

The only thing that was crashing was the folder renaming, after which they were out of sync and I have/had no idea how to get out of that state afterwards.

**Comment by chrislusf** [comment] 2022-01-02 05:17
Feedback is important. Nice to know your thoughts and ideas! Thanks! 

You can use 2 one-way processes for each pair, e.g.:
```
weed filer.sync -a app1:8888 -b app2:8888 -isActivePassive && weed filer.sync -a app1:8888 -b app3:8888 -isActivePassive
```

**Comment by KevinBLT** [comment] 2022-01-02 08:59
Thanks, I will try it this way using pulls and test it with not real data, so if the error reoccurs I can tell exactly what I tried!

Nonetheless: 
  Is there a command or method to resync the clusters in this case?

**Comment by chrislusf** [comment] 2022-01-02 11:46
> Is there a command or method to resync the clusters in this case?

did not happen before so no tools for this yet.

**Comment by KevinBLT** [comment] 2022-01-02 15:04
Hey, sorry but now I have another problem that I am not able to solve, I wanted to de clean start to test and maybe reproduce the error, so I deleted the files that I used before. Now the volume server never creates any files at all?

```
master: localhost:9333 
> volume.list
Topology volumeSizeLimit:30000 MB hdd(volume:0/0 active:0 free:0 remote:0) ssd(volume:0/30 active:0 free:30 remote:0)
  DataCenter app1 ssd(volume:0/30 active:0 free:30 remote:0)
    Rack 1 ssd(volume:0/30 active:0 free:30 remote:0)
      DataNode app1:8080 ssd(volume:0/30 active:0 free:30 remote:0)
        Disk ssd(volume:0/30 active:0 free:30 remote:0)
        Disk ssd total size:0 file_count:0 
      DataNode app1:8080 total size:0 file_count:0 
    Rack 1 total size:0 file_count:0 
  DataCenter app1 total size:0 file_count:0 
total size:0 file_count:0 
```

But when 
```
$ curl http://localhost:9333/dir/assign
$ {"error":"No free volumes left for {\"replication\":{},\"ttl\":{\"Count\":0,\"Unit\":0}}"}
```

The `dir` used by volume is completely empty normally there would be the volume files?

**Comment by KevinBLT** [comment] 2022-01-02 16:56
Well okay, I had to remove -rack X -datacenter -disk and it was working again. Is this by intention?
I wonder, because I am sure I have run it like that before too.

**Comment by KevinBLT** [comment] 2022-01-02 17:37
Okay some results  I used python smallfile (https://github.com/distributed-system-analysis/smallfile)

Mounted folder `/srv/app/` and synced with `weed filer.sync -a -b isActivePassive` as you suggested from all nodes.

`python3 ~/tmp/smallfile/smallfile_cli.py --operation create --threads 2 --file-size 128 --files 2048 --top /srv/app/tmp --network-sync-dir /tmp/smf`

Doing `tree` in the folder `tmp` (Server1-3 = app1-3):
app1 `tree [ ... ] 96 directories, 4096 files`
app2 `tree [ ... ] 96 directories, 2575 files`
app3 `tree [ ... ] 96 directories, 3224 files`

The python smallfile test is good because it create a lot of small files and different directories which is similar to my case.
Here it is out of sync right after creating the files - without a top directory rename.

**Comment by KevinBLT** [comment] 2022-01-02 17:40
After going `cd ..`  and `mv tmp xyz` then `tree`:
app1: `98 directories, 4096 files`
app2: `103 directories, 4135 files`
app3: `104 directories, 4134 files`

**Comment by chrislusf** [comment] 2022-01-03 06:15
How did you get around this error `{"error":"No free volumes left for {\"replication\":{},\"ttl\":{\"Count\":0,\"Unit\":0}}"}`? You would need to have at least one hdd disk drive.

Could you please try it with the 2.84 version for the metadata sync?

**Comment by KevinBLT** [comment] 2022-01-03 11:39
Yes, I got around this error removing the `-disk ssd`. I was not aware that the default will always be hdd. Maybe it should take the first available in this case? Would clean up the status to show the reality (no hdds involved)

I will test the new version and if it makes a difference this week :-)

**Comment by KevinBLT** [comment] 2022-01-09 11:18
Hi again, so I tested 2.84 - what now works a lot better and faster is the inital creation of the files, the synced filers catch up with almost 0 latency so that I end up with :

app1 `tree [ ... ] 96 directories, 4096 files`
app2 `tree [ ... ] 96 directories, 4096 files`
app3 `tree [ ... ] 96 directories, 4096 files`

It took maybe < 10seconds from 0 to `96 directories, 4096 files` on the other filers - allright!

So now I rename the folder `tmp` to `x` on app1 (`mv tmp x`)

now on app1 there is only the `x` directory again with `96 directories, 4096 files`.
On the other filers they will say this (both app2 AND app3 are equaly out of sync now):
```
ls
tmp  x
cd x
tree
[...] 80 directories, 2624 files 
```

Is there any connection between these numbers? What do you think?

Also, if I go into the "ghost directory" `tmp` (which is no NOT present on app1 anymore), 
on both servers app2 and app3 it shows:
`21 directories, 1473 files`

**Comment by KevinBLT** [comment] 2022-01-09 11:24
Okay, so, when I do `systemctl restart seaweedfs-sync@app1` on app3, all filers are in sync again, even on app2, where I did not restart anything. 

(`seaweedfs-sync@.service` contains the `weed filer.sync -a %i:8888 -b %H:8888 -isActivePassive` command)

**Comment by chrislusf** [comment] 2022-01-10 06:34
Tried to copy and rename a fairly large folder. I could not reproduce this yet.

Could you please try it with 2.85? Seems the bug is in `weed mount` and there is a fix about renaming in 2.85

**Comment by KevinBLT** [comment] 2022-01-10 09:36
Thanks Christ - I will check it out this week and return back!

From the commits to 2.85 it looks like it could possibly solve another error I got yesterday but had no way to reproduce in any way.
One was a directory that could not be created anymore via mount (`mkdir` said `No such file or directory`),
the other one was a (text) file that had the last characters twice, like two processes wrote to it simultaneously.

Good thing is I was always able to solve it by a restart of filer.

**Comment by chrislusf** [comment] 2022-01-11 07:20
Could you please try it without loop? Instead of A<=>B<=>C<=>A, just do A<=>B<=>C.

This may resolve some race conditions.

**Comment by chrislusf** [comment] 2022-01-23 07:56
closing if no more updates.

**Closed by chrislusf** 2022-01-23 07:56 UTC

**Comment by KevinBLT** [comment] 2022-01-23 16:32
Hey Chris, sorry I was not fit last Week. So I did the same again and it is less "off" after renaming, although not the same:
- app1 (where the mv command was issued) : `97 directories, 4096 files`
- app2: `102 directories, 4097 files`
- app3: `102 directories, 4097 files`
-----------------
But wait! This time, it caught up after a minute or so! Maybe something of the Every-17-Minute job fixed something?

Not sure, but seems like it's fixed although it needs around ~1-2 minutes to remove the orphaned files and directories.
