### ISSUE TITLE
Docker Image for ARM (Raspberry PI)

### ISSUE THREAD

**Issue by mario-tux** [chrislusf/seaweedfs#1220] opened 2020-03-07 08:42 UTC
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs

**Describe the bug**
I'm trying to deploy seaweedfs on a swarm with 3 nodes: two x86 servers and one raspberry pi 2 (to get a majority in case of a server fault). I'm was not able to launch the docker container on the rpi. In the Docker Hub builds page I can't see an ARM build. In report https://github.com/chrislusf/seaweedfs/issues/1162 you suggest to use `chrislusf/seaweedfs:dev` tag but it doesn't help me.

On the rpi:
```
# docker run chrislusf/seaweedfs -ti
standard_init_linux.go:211: exec user process caused "exec format error"
# docker run chrislusf/seaweedfs:dev -ti
standard_init_linux.go:211: exec user process caused "exec format error"
```
Both the commands launch `weed` command, without parameters, on the x86 servers.

**Comment by thiscantbeserious** [comment] 2020-03-07 09:21
I manually build an armhf binary just fine (armv7+) not sure about armv7 tought.

I'll shortly create an layerized multiarch docker-image that I'll upload to Docker Hub and send the Dockerfile as a PR to chris that will include arm(v7+) support as well.

**Comment by thiscantbeserious** [comment] 2020-06-15 10:12
Eh, sorry guys was a bit busy lately. Since Chris officially publishes ARM releases now and finished his CSI-Driver for Kubernetes I'm going to get back to this soon. In the meantime just use the ARM builds directly now. :)

**Comment by Gronis** [comment] 2020-06-30 20:28
There are binary releases for multiple architectures, but the docker image only builds for `amd64` (x86 64-bit) processors. The problem is that `chrislusf/seaweedfs` docker images uses `frolvlad/alpine-glibc`, which is also an `amd64` only build.

I forked the alpine-glibc and built a base image for `amd64`, `arm64`, `armv7`, and `armv6`. Then I forked `seaweedfs` and changed the Dockerfile somewhat to support more cpu architechtures. I have not tested `armv6` build, but the other builds seem to work. I do not have a running seaweed cluster as of now though so my testing is very shallow, but if you want to test the images, you can find the docker image here: https://hub.docker.com/r/gronis/seaweedfs/tags

**Comment by Gronis** [comment] 2020-06-30 21:21
Actually, I don't think that having glib adds anything since the build of seaweed is happening outside the container. I used alpine image directly and it seams to work as well. Will post a PR with a multiarch supported build.

**Comment by chrislusf** [comment] 2020-06-30 23:35
Thanks! Merged!

**Closed by chrislusf** 2020-06-30 23:35 UTC
