### ISSUE TITLE
What is the best volume service configuration?

### ISSUE THREAD

**Issue by noneusa** [chrislusf/seaweedfs#2600] opened 2022-01-19 05:42 UTC
1. increase the number of volumes and limit the volume file size, for example, 100T of data 1000+ volumes each volume file size is limited to 100GB
```
weed master -mdir=master -volumeSizeLimitMB=102400 ...
volume -max=2000 ...
```

2. reduce the number of volumes and increase the volume file size, for example, 100T data 100 volumes each volume file size 1TB+
```
weed master -mdir=master -volumeSizeLimitMB=1024000 ...
weed volume -max=100 ...
```

Which of these two options is better?

Now i use option 2,

There are about 100T of image files stored, the number of volumes is 200, and the dat file of a single volume is about 635GB

A few hours after starting the service, the physical 128G memory of the server was completely used up, and the weed process of the volume service only used 4G physical memory.

Using Microsoft's RamMap tool to view the memory footprint, it is mainly occupied by Mapped File,

The only way to release memory is through Empty Working Sets of RamMap tool, or restarting the volume server process.

Does the volume service read the volume file and then keep occupying it without releasing it? I now can only be regular memory release manual operation to work

**Comment by chrislusf** [comment] 2022-01-19 05:46
are you on windows? Maybe there are some file closing leak on windows.

**Comment by noneusa** [comment] 2022-01-19 06:10
yes,on windows2019 server
process worker set never released

**Comment by chrislusf** [comment] 2022-01-19 06:25
On windows, the file close is a bit different.

Does the tool show what is the name of the mapped file?

**Comment by noneusa** [comment] 2022-01-19 06:55
I just released the memory an hour ago, and now using 11G of memory
If needed, I'll take a screenshot later when I use 100G of memory

![image](https://user-images.githubusercontent.com/95112936/150078661-1e2fa7e9-410d-4344-bb72-b9864dc3cf67.png)
![image](https://user-images.githubusercontent.com/95112936/150079167-744d36a5-fceb-4a1f-a3bf-91ff23858cd5.png)
![image](https://user-images.githubusercontent.com/95112936/150079345-bf59f0ad-8ce2-4101-b280-318765036714.png)
![image](https://user-images.githubusercontent.com/95112936/150079432-1c3bcee5-c80b-4c3b-9259-fc84d9bb8392.png)

**Comment by chrislusf** [comment] 2022-01-19 09:13
do you run any admin scripts? If so, try to disable them and see whether it helps. I need to see which process is leaking file descriptors.

**Comment by chrislusf** [comment] 2022-01-19 09:18
does the server crash? I saw https://stackoverflow.com/questions/63667023/get-name-of-memory-mapped-file that it is ok.

**Comment by noneusa** [comment] 2022-01-19 10:01
i;m not run any scripts, i'm working on find which process Mapped File,
No results yet, but when I restarted the volume server , the Mapped File and memory will be released immediately

the server not crash,but when memory(128G) full, other process will crach

**Comment by chrislusf** [comment] 2022-01-19 10:26
Is it possible to have a graph of the mapped file activities, for file counts and for memory size?
That would help to understand the root cause.

**Comment by noneusa** [comment] 2022-01-19 12:58
i don't have time-series graph


just 1.dat have thousands of records,
![image](https://user-images.githubusercontent.com/95112936/150134317-cc3ecd04-f6ab-4082-9794-443a531dff71.png)
![image](https://user-images.githubusercontent.com/95112936/150134769-cec6f079-9567-445a-9286-994eb1aa9c45.png)

![image](https://user-images.githubusercontent.com/95112936/150135033-925d6bf6-51d8-401e-acc7-9371d19c2142.png)

**Comment by noneusa** [comment] 2022-01-19 18:30
100GB memory used used
![image](https://user-images.githubusercontent.com/95112936/150192234-6c756b4a-eb18-417a-8cca-53925aa8a0b6.png)

![image](https://user-images.githubusercontent.com/95112936/150191984-da14c25f-6f25-41b3-b572-194de1b4b0a7.png)

**Comment by noneusa** [comment] 2022-01-19 18:33
Empty Working Sets, memory release
![image](https://user-images.githubusercontent.com/95112936/150192509-0ef799f6-dd34-47de-9717-9ad44b4578ef.png)

**Comment by chrislusf** [comment] 2022-01-20 07:53
what is the use case and traffic pattern?

**Comment by noneusa** [comment] 2022-01-20 11:26
http service after nginx

**Comment by chrislusf** [comment] 2022-01-20 13:56
How often is the deletions, reads, writes?

**Comment by noneusa** [comment] 2022-01-20 13:59
no delete, 95% read, low writes

**Comment by chrislusf** [comment] 2022-01-22 10:22
I think these are just normal caching done by windows for a normal file read operation. There are nothing to optimize there. 
"Mapped Files" may be the wrong thing to watch.

If "Mapped Files" is the culprit, you may have to switch to Linux.

**Closed by chrislusf** 2022-01-22 10:22 UTC
