### ISSUE TITLE
SeaweedFS RocksDB filer immediately eats all RAM on startup (OOM)

### ISSUE THREAD

**Issue by zcalusic** [chrislusf/seaweedfs#2650] opened 2022-02-08 12:17 UTC
First of all, thank you for this amazing software @chrislusf!

Here's the showstopper problem for us: SeaweedFS RocksDB filer has some nasty bug, where after starting it (for the first time) it almost instantly eats all the RAM on the machine (OOM condition). It can be easily reproduced with the official SeaweedFS Docker image that has support for RocksDB filer like this:
```
# cat /root/.seaweedfs/filer.toml 
[rocksdb]
enabled = true
dir = "/tmp/weed"

docker run -it --rm --memory=8g -v /root/.seaweedfs:/root/.seaweedfs -v /tmp/weed:/tmp/weed chrislusf/seaweedfs:2.88_large_disk_rocksdb server -filer
```
Notice that memory limiter in the above line is only there to protect Docker host machine from going out of memory. When I ran it without that, it OOM-ed a 128GB RAM server in a matter of seconds, so be careful when running it!

In /tmp/weed it can be seen that RocksDB has created its initial file structure, and container manages to log just several of these lines before it's killed:
```
I0208 11:40:31     1 meta_aggregator.go:113] connecting to peer filer 172.17.0.2:8888: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:18888: connect: connection refused"
I0208 11:40:33     1 meta_aggregator.go:113] connecting to peer filer 172.17.0.2:8888: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:18888: connect: connection refused"
I0208 11:40:34     1 meta_aggregator.go:113] connecting to peer filer 172.17.0.2:8888: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.17.0.2:18888: connect: connection refused"
```
SeaweedFS version 8000GB 2.88 72700672 linux amd64. Host OS is Debian 10 Buster.

I tried compiling SeaweedFS with RocksDB support myself, just in case, unfortunately with the same outcome as described above (OOM). Of many filer databases available, after extensive testing, it seems RocksDB would be a best fit for our use case (lots of files added, and lots of files deleted!) due to native TTL support. Thank you for looking into this issue!

Cc: @qieqieplus

**Comment by qieqieplus** [comment] 2022-02-08 12:25
What's the version of your rocksdb?

**Comment by zcalusic** [comment] 2022-02-08 12:42
Hello @qieqieplus, thanks for looking into this. :+1: 

Well, it's not technically mine, since this is the official docker image we're talking about.

But, if I suspect right that the official image is built from [this Dockerfile](https://github.com/chrislusf/seaweedfs/blob/21aaa4c1f1c85486b5148605f8cb15db3f870be2/docker/Dockerfile.rocksdb_large#L6) then it's v6.22.1.

**Comment by qieqieplus** [comment] 2022-02-08 13:14
Have you tried using version before 6? Since gorocksdb is no longer maintained by its owner before RocksDB v6 released, it may not work well with C API of latest version of RocksDB.

**Comment by qieqieplus** [comment] 2022-02-08 14:42
I'm not working on SeaweedFS for a while.  I'm using old SeaweedFS v2.45(with some unpublished modification) + RocksDB v6.23.3 (actually my fork from v6.23.1 and PR got merged in v6.23.3), also my own fork of [gorocksdb](https://github.com/qieqieplus/gorocksdb) in production enviroment. But it cannot be easily reproduced by someone else.

I'll test official docker build some other day and I'll update in this thread if I find anything.

**Comment by chrislusf** [comment] 2022-02-09 08:03
somehow I got this error:
![Screen Shot 2022-02-09 at 12 02 47 AM](https://user-images.githubusercontent.com/1543151/153149248-a3ae11f1-da2b-4b48-be84-7dc98054f3d3.png)

**Comment by qieqieplus** [comment] 2022-02-09 08:26
By default rocksdb is built with -march=native, try PORTABLE=1 before make

**Comment by chrislusf** [comment] 2022-02-09 08:29
> By default rocksdb is built with -march=native, try PORTABLE=1 before make

send a PR?

**Comment by chrislusf** [comment] 2022-02-09 09:29
like this? eb39f783968b118a8eb84a7b389f30058c3892ba

**Comment by qieqieplus** [comment] 2022-02-09 10:36
> ```
> docker run -it --rm --memory=8g -v /root/.seaweedfs:/root/.seaweedfs -v /tmp/weed:/tmp/weed chrislusf/seaweedfs:2.88_large_disk_rocksdb server -filer
> ```

Yes, that should fix the case when you build in one machine(e.g. AVX512 support), and execute in another one (without AVX512 support), at the cost of performace loss.

However I failed to reproduce the OOM case in my dev environment.

**Comment by chrislusf** [comment] 2022-02-11 11:07
closing if no upates. @zcalusic

**Closed by chrislusf** 2022-02-11 11:07 UTC

**Comment by zcalusic** [comment] 2022-02-11 13:19
I'm afraid it didn't help. :cry:

For a while I tested the official image again, not noticing that it hasn't been updated. :confused:

Then I rebuilt my own image with PORTABLE=1, and also there's no change, it still eats RAM in a matter of seconds.

One thing is sure, it eats memory exactly while it's logging those "connection refused" errors, so the bug is somehow connected to that.

I tried adding ```-memprofile``` but unfortunately that ends with empty profile output file, probably because the process is violently killed by the kernel, so it doesn't get a change to write profile out.

I also tried catching the profile by means of ```wget http://127.0.0.1:8080/debug/pprof/heap``` (if that's how it's also supposed to work?), but all i get is 400 Bad Request.

If there's anything else I can do to help, I'm game, but currently... out of ideas, I'm afraid.

**Comment by linxGnu** [comment] 2022-02-11 13:33
I dont know why I was tagged here. By the way, as author of grocksdb, I think (just imho) that maybe there is something wrong at invoker side, some common errors like: forget calling release c pointer, data race.

I used grocksdb for heavy write app, let it run for several month without any problem.

**Comment by qieqieplus** [comment] 2022-02-15 08:57
Unfortunately pprof is unable to trace cgo side memory allocations, so it won't help if the OOM comes from RocksDB internally.
It's also unlikely to be the errors mentioned above, forget calling release c pointer i.e. memory leak is a slow process, not instant OOM.
My closest guess is a type conversion bug, like passing a int32 size as int64/ size_t, it will not cause fatal memory access error, but result in a random huge value which potentially leads to huge memory allocation.
But I'm unable to reproduce this problem, so I guess there're still some unknown conditions.

**Comment by zcalusic** [comment] 2022-02-15 09:08
Thank you @qieqieplus for all your involvement, you're of course right once again, there's something really subtle going on here, and it's probably cgo related.

But, since Chris has closed this issue and obviously doesn't want to deal with it anymore, I decided to not pursue RocksDB based solution anymore. Of all filer stores available, it seems none is working correctly for my use case, so I'll probably develop a custom solution.
