### ISSUE TITLE
[mount] git on fuse no longer works

### ISSUE THREAD

**Issue by wozeparrot** [chrislusf/seaweedfs#3351] opened 2022-07-22 20:23 UTC
**Describe the bug**
Since `mount2` was made default in `2.91`, I have found that git repositories no longer work on the FUSE mount.

I have bisected the `mount2` commits down to be3fc7739161a29e57ae1481358656af385b1002 as the initial bad commit with git commits working correctly before this commit landed and they also work correctly if mounted with `mount` instead of `mount2`.

git throws this error when trying to commit on seaweedfs built on be3fc7739161a29e57ae1481358656af385b1002:
![image](https://user-images.githubusercontent.com/25372613/180532440-f88ee114-aeca-4521-b88c-ef30d8c847f0.png)

git throws a different error when trying to commit on seaweedfs built from master:
![image](https://user-images.githubusercontent.com/25372613/180520079-5fc3bede-0562-4035-91dc-e15018be667e.png)

**System Setup**
Start seaweedfs server: `weed server -dir=./data/ -filer`
Mount: `weed mount -dir ./mnt/` or `weed mount2 -dir ./mnt/` if mounting the bisected commit

Create a git repo in the mount with a file and try to do a commit:
```shell
cd ./mnt/
mkdir test && cd test
git init
touch a
git add a
git commit -m "test"
```
or do it in one line if testing the bisected commit or else the mount will SEGV
```shell
cd ./mnt/
mkdir test && cd test && git init && touch a && git add a && git commit -m "test"
```

Watch as it fails with the error above.

**Expected behavior**
The git commit does not fail.

**Additional context**
```
# weed version [built on commit 0716092b396941e07ab2e41e782641ae658b3793]
version 30GB 3.16  linux amd64
# weed version (bisected) [built on commit be3fc7739161a29e57ae1481358656af385b1002]
version 30GB 2.90  linux amd64
```

**Comment by chrislusf** [comment] 2022-07-23 01:20
Added a fix. Can you try https://github.com/chrislusf/seaweedfs/releases/tag/dev

**Comment by wozeparrot** [comment] 2022-07-23 01:27
Still running into the same issue, but it seems that if I try to commit over and over again in quick succession, sometimes it will succeed.

![image](https://user-images.githubusercontent.com/25372613/180585142-319c68c7-247d-4244-af83-adcd3a00eb0f.png)

**Comment by wozeparrot** [comment] 2022-07-23 02:23
> Added a fix. Can you try [`dev` (release)](https://github.com/chrislusf/seaweedfs/releases/tag/dev)

This commit seems to have made cloning large git repos slightly more consistent, but sometimes they will still fail with either:
```
error: failed to read delta-pack base object ca3167fb83a89814634a7ef33af0425f60a97e77
fatal: unpack-objects failed
```
or
```
fatal: bad object 02f0038db6e41ccc7f86fb68624b8271a289388e
error: remote did not send all necessary objects
```
or
```
fatal: serious inflate inconsistency
fatal: fetch-pack: invalid index-pack output
```

I haven't found a way to consistently reproduce it as it seems very sporadic. One way that I have found that will eventually hit an issue is trying to fetch AOSP source. Might be related to #2305?

**Comment by paularlott** [comment] 2022-07-23 14:29
I have a large git repository, approx 2GB, which if I clone to a seaweedfs mount either gets stuck Resolving deltas or if it does work then without touching anything `git status` shows that one file, a symbolic link, has been changed.

However I've not managed to create a test case that I can give to you.

**Comment by wozeparrot** [comment] 2022-07-23 21:05
Something interesting to note is that this command chain with fail:
```shell
# in mount
➜ mkdir test && cd test && touch a && git init && git add a && git commit -m "test"
Initialized empty Git repository in /mnt/test/.git/
error: invalid object 100644 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 for 'a'
error: invalid object 100644 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 for 'a'
error: Error building trees
```
while adding a `sleep 1` between the `git add` and the `git commit` makes it fail with a different error:
```shell
# in mount
➜ mkdir test && cd test && touch a && git init && git add a && sleep 1 && git commit -m "test"
Initialized empty Git repository in /mnt/test/.git/
fatal: cannot update ref 'refs/heads/main': trying to write ref 'refs/heads/main' with nonexistent object 57d6c3c2ee0bd46e7778034856a0f77de8bedcf3
```
but if there are two git commits in the same second the first one will fail but the second one will succeed:
```shell
# in mount
➜ mkdir test && cd test && touch a && git init && git add a && sleep 1 && git commit -m "test" || git commit -m "test"
Initialized empty Git repository in /mnt/test/.git/
fatal: cannot update ref 'refs/heads/main': trying to write ref 'refs/heads/main' with nonexistent object b9202c4f5f922d4072885ebb12d4802b758ad6c0
[main (root-commit) b9202c4] test
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 a
```

**Comment by chrislusf** [comment] 2022-07-24 01:45
Seems only reproducible on linux. Added a few fixes. Please help to test with the dev version.

**Comment by wozeparrot** [comment] 2022-07-24 02:01
With the new dev version it seems like git commits now work properly, but the issue with sporadic large git clones failing still exists but it happens less frequently now.

**Comment by chrislusf** [comment] 2022-07-24 02:14
any large git repo to test with?

**Comment by wozeparrot** [comment] 2022-07-24 02:16
Upon further testing it seems like large git clones are working fine now, the servers I was testing weren't running the right version.

**Comment by chrislusf** [comment] 2022-07-24 02:22
@wozeparrot thanks for the quick confirmation!

@paularlott does it work for you now?

**Comment by paularlott** [comment] 2022-07-24 03:14
@chrislusf It doesn't look like it has resolved the issue I'm seeing.

I tried a git clone however it's stopping dead at the Resolving deltas step, no errors, it just stops with a very high IO wait.

I also tried rsync from my main drive to the SeaweedFS mount and git status on the copy is reporting that the sym link has changed.

**Comment by chrislusf** [comment] 2022-07-24 05:16
@paularlott any large git repo for me to try?

**Comment by paularlott** [comment] 2022-07-24 05:18
I've not found one yet that I can give you, I'm still looking.

**Comment by chrislusf** [comment] 2022-07-24 05:19
Does it work on smaller git repo? Is it related to git LFS?

**Comment by paularlott** [comment] 2022-07-24 05:40
Yes, it works for every other repo I've tried, but they are all a lot smaller. I don't think it's LFS related as another repo using LFS is fine.

**Comment by paularlott** [comment] 2022-07-24 10:26
@chrislusf For the sym link error I've just realised it is as simple as the following to replicate it, I'm not sure why this didn't show it up before:

```
mkdir test
cd test
git init
touch a
ln -fs a b
git add a
git add b
git commit -m "test"
git status
```

The git status shows:

```
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   b
```

If I do the same on the local drive then b isn't flagged as modified.

I'm on ubuntu 22.04 using the last dev build of SeaweedFS.

I'm still trying to find a way to replicate the stall.

**Comment by paularlott** [comment] 2022-07-24 15:20
@chrislusf I'm very sorry but it looks like I have a failed network card, I moved my tests to another machine and I can pull the repository without the stall. I'm not sure why it's only showing up with SeaweedFS.

So it's only the symlink issue that's remaining.

**Comment by wozeparrot** [comment] 2022-07-24 15:39
Upon further testing it appears that the failed git clone issue has appeared again, but I found that it only happens my cluster which uses slower drives than the ones I have in my development machine.

```shell
➜ repo init -u https://github.com/LineageOS/android.git -b lineage-19.1 --no-use-superproject -v
Downloading Repo source from https://gerrit.googlesource.com/git-repo
Cloning git repository https://gerrit.googlesource.com/git-repo
Downloading clone bundle https://gerrit.googlesource.com/git-repo/clone.bundle
repo: error: "git" failed with exit status 1
  cwd: /mnt/tmp/wozeroid/wozeroid/.repo/repo
  cmd: ['git', 'fetch', '--quiet', '/mnt/tmp/wozeroid/wozeroid/.repo/repo/.git/clone.bundle', '+refs/heads/*:refs/remotes/origin/*', '+refs/tags/*:refs/tags/*']
  stderr:
  >> error: inflate: data stream error (incorrect header check)
  >> error: inflate: data stream error (incorrect header check)
  >> error: inflate: data stream error (incorrect header check)
  >> fatal: serious inflate inconsistency
  >> fatal: serious inflate inconsistency
  >> fatal: serious inflate inconsistency
  >> error: inflate: data stream error (unknown compression method)
  >> warning: die() called many times. Recursion error or racy threaded death!
  >> fatal: serious inflate inconsistency
  >> error: index-pack died
fatal: double check your --repo-rev setting.
fatal: cloning the git-repo repository failed, will remove '.repo/repo'
```

I found that I can somewhat reliably (about 1/5 times) reproduce the issue by trying to initialize a `git-repo` project:
```shell
# have git-repo installed
mkdir test && cd test
repo init -u https://github.com/LineageOS/android.git -b lineage-19.1 --no-use-superproject -v
# if it succeeds remove the .repo directory
```

**Comment by wozeparrot** [comment] 2022-07-25 01:32
Simpler test case that I've found
```shell
mkdir test && cd test
curl -O "https://storage.googleapis.com/gerritcodereview/gerrit_git-repo_clone.bundle"
git init

# this command will fail
git fetch ./gerrit_git-repo_clone.bundle
```

Another thing that I've noticed is that it only fails if mounting the cluster remotely, if I mount the cluster on the same machine that filer is running on it doesn't fail.

**Comment by chrislusf** [comment] 2022-07-25 01:40
Tried to debug the symlink problem. I could not tell why git considers b is modified. I guess it is about some time comparison. But I do not tell the difference with common file system.

```
> GIT_TRACE=2 GIT_CURL_VERBOSE=2 GIT_TRACE_PERFORMANCE=2 GIT_TRACE_PACK_ACCESS=2 GIT_TRACE_PACKET=2 GIT_TRACE_PACKFILE=2 GIT_TRACE_SETUP=2 GIT_TRACE_SHALLOW=2 git status
18:31:54.504452 trace.c:387             setup: git_dir: .git
18:31:54.504958 trace.c:388             setup: git_common_dir: .git
18:31:54.504968 trace.c:389             setup: worktree: /Users/chrislu/tmp/mm/test
18:31:54.504971 trace.c:390             setup: cwd: /Users/chrislu/tmp/mm/test
18:31:54.504975 trace.c:391             setup: prefix: (null)
18:31:54.505303 chdir-notify.c:67       setup: chdir from '/Users/chrislu/tmp/mm/test' to '/Users/chrislu/tmp/mm/test'
18:31:54.505321 git.c:455               trace: built-in: git status
18:31:54.536869 read-cache.c:2398       performance: 0.006502000 s:  read cache .git/index
18:31:54.554564 read-cache.c:1690       performance: 0.017119000 s:  refresh index
18:31:54.558796 diff-lib.c:266          performance: 0.000423000 s:  diff-files
18:31:54.584727 unpack-trees.c:1802     performance: 0.000009000 s:    traverse_trees
18:31:54.585108 unpack-trees.c:418      performance: 0.000361000 s:    check_updates
18:31:54.585144 unpack-trees.c:1892     performance: 0.001730000 s:   unpack_trees
18:31:54.585153 diff-lib.c:629          performance: 0.019750000 s:  diff-index
18:31:54.585841 name-hash.c:607         performance: 0.000014000 s:  initialize name hash
18:31:54.590437 read-cache.c:3072       performance: 0.003064000 s:  write index, changed mask = 2
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   b

no changes added to commit (use "git add" and/or "git commit -a")
18:31:54.594870 trace.c:487             performance: 0.105520000 s: git command: git status
```

**Comment by paularlott** [comment] 2022-07-25 02:09
I tried the same set of operations using rclone to mount a s3 bucket off SeaweedFS, that doesn't exhibit the git link issue, so whatever it is it is related to weed mount. I can't see a difference, however I don't think it's the time stamp.

**Comment by chrislusf** [comment] 2022-07-27 01:15
Did you find any simple steps to reproduce the symlink problem?

**Comment by paularlott** [comment] 2022-07-27 01:28
Testing again with the latest release it's still present and the only way I can reproduce it is with the steps from https://github.com/chrislusf/seaweedfs/issues/3351#issuecomment-1193289253 I can't seem to reproduce it outside of git,  probably because it's specific to the way git works.

I suspect it's something to do with lstat call which I think git does on the files.

I did notice that if I do stat on b on a seaweedfs mount I get:

```
  File: b -> a
  Size: 0         	Blocks: 0          IO Block: 512    symbolic link
Device: 2dh/45d	Inode: 13954937719265252888  Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-07-27 09:17:25.000000000 +0800
Modify: 2022-07-27 09:17:25.000000000 +0800
Change: 2022-07-27 09:17:25.000000000 +0800
 Birth: -
```

while on local disk I get:

```
  File: b -> a
  Size: 1         	Blocks: 0          IO Block: 4096   symbolic link
Device: fd00h/64768d	Inode: 2097697     Links: 1
Access: (0777/lrwxrwxrwx)  Uid: ( 1000/    paul)   Gid: (  999/  docker)
Access: 2022-07-27 09:20:33.355045905 +0800
Modify: 2022-07-27 09:20:29.939043475 +0800
Change: 2022-07-27 09:20:29.939043475 +0800
 Birth: 2022-07-27 09:20:29.939043475 +0800
```

Size is 0 vs 1
Birth is missing on the seaweedfs volume
timestamp is less accurate on seaweedfs.

If I do stat on the file a, then both return Size as 0 as I'd expect.

I'm not sure if any of these are the cause, however at this point I'd take a guess Size might have something to do with it.

**Comment by wozeparrot** [comment] 2022-07-27 01:36
Doing a quick search reveals this: https://github.com/upspin/upspin/issues/619 which shows the same behavior that we are experiencing here.

**Comment by chrislusf** [comment] 2022-07-27 06:23
added a fix. seems related to symlink size.

**Closed** 2022-07-27 06:33 UTC
