### ISSUE TITLE
weed version2.3.9 mount memory leak.

### ISSUE THREAD

**Issue by xstone0527** [chrislusf/seaweedfs#1994] opened 2021-04-14 04:24 UTC
Sponsors SeaweedFS via Patreon https://www.patreon.com/seaweedfs
Report issues here. Ask questions here https://stackoverflow.com/questions/tagged/seaweedfs
Please ask questions in https://github.com/chrislusf/seaweedfs/discussions

example of a good issue report:
https://github.com/chrislusf/seaweedfs/issues/1005
example of a bad issue report:
https://github.com/chrislusf/seaweedfs/issues/1008

**Describe the bug**

**System Setup**
- List the command line to start "weed master", "weed volume", "weed filer", "weed s3", "weed mount".
- OS version
- output of `weed version`
- if using filer, show the content of 

OS
```
root@jp-op-admin03:~# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.6 (stretch)
Release:        9.6
Codename:       stretch
root@jp-op-admin03:~#
root@jp-op-admin03:~# uname -a
Linux jp-op-admin03 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
root@jp-op-admin03:~#
```
Weed Version
"weed master", "weed volume", "weed filer", "weed s3"  used:
```
root@jp-cmn-seaweedfs01:~# /usr/local/seaweedfs/weed version
version 30GB 2.05 898db14 linux amd64
root@jp-cmn-seaweedfs01:~# 
```
"weed mount" used:
```
root@jp-op-admin03:~# /usr/local/seaweedfs/weed version
version 30GB 2.39 742ab1e linux amd64
root@jp-op-admin03:~#
```
filer parameter:
```
# A sample TOML config file for SeaweedFS filer store
# Used with "weed filer" or "weed server -filer"
# Put this file to one of the location, with descending priority
#    ./filer.toml
#    $HOME/.seaweedfs/filer.toml
#    /etc/seaweedfs/filer.toml

####################################################
# Customizable filer server options
####################################################
[filer.options]
# with http DELETE, by default the filer would check whether a folder is empty.
# recursive_delete will delete all sub folders and files, similar to "rm -Rf"
recursive_delete = false
# directories under this folder will be automatically creating a separate bucket
buckets_folder = "/buckets"
buckets_fsync = [          # a list of buckets with all write requests fsync=true
        "important_bucket",
        "should_always_fsync",
]

####################################################
# The following are filer store options
####################################################

[leveldb2]
# local on disk, mostly for simple single-machine setup, fairly scalable
# faster than previous leveldb, recommended.
enabled = true
dir = "/data/seaweedfs/filer"


[redis2]
enabled = false
address  = "localhost:6379"
password = ""
database = 0

[redis_cluster2]
enabled = false
addresses = [
    "localhost:30001",
    "localhost:30002",
    "localhost:30003",
    "localhost:30004",
    "localhost:30005",
    "localhost:30006",
]
password = ""
# allows reads from slave servers or the master, but all writes still go to the master
readOnly = true
# automatically use the closest Redis server for reads
routeByLatency = true

[elastic7]
enabled = false
servers = [
    "http://localhost1:9200",
    "http://localhost2:9200",
    "http://localhost3:9200",
]
username = ""
password = ""
sniff_enabled = false
healthcheck_enabled = false
# increase the value is recommend, be sure the value in Elastic is greater or equal here
index.max_result_window = 10000
```

**Comment by xstone0527** [comment] 2021-04-14 04:24
![1](https://user-images.githubusercontent.com/11675450/114654264-5e335680-9d1c-11eb-86d9-4e72a0541410.jpg)
![2](https://user-images.githubusercontent.com/11675450/114654267-5ffd1a00-9d1c-11eb-85bb-0ff60df7aef9.jpg)
![3](https://user-images.githubusercontent.com/11675450/114654268-6095b080-9d1c-11eb-9f8c-036636e43a5a.jpg)

**Comment by chrislusf** [comment] 2021-04-14 05:48
* Need to make sure the `weed version` are consistent for all instances.
* How to reproduce the leak? What kind of files, e.g., size, amount, etc. And what kind of operations?

**Comment by xstone0527** [comment] 2021-04-14 06:40
all instances include master，volume，filer and s3 roles？the file size is 4MB and 20MB,running with qclond cos migration tools。

**Comment by chrislusf** [comment] 2021-04-14 08:18
* yes
* Need a way to reproduce.  If possible, make a reproducible case via docker image or docker compose file.

**Comment by chrislusf** [comment] 2021-04-14 08:41
you may want to try the dev version, which has some more memory fixes https://github.com/chrislusf/seaweedfs/releases/tag/dev

Should be good if just using the dev version for the `weed mount`

**Comment by xstone0527** [comment] 2021-04-14 09:14
Just now,Im upgrade weed binary package from 2.05 to 2.39 with master,volume,filer,s3 roles and remount client with command line weed mount.i`m sure all roles running the same version 2.39,but memory leak Doesn't seem to be resolved。
Read-only scene，about 100 million files。

**Comment by xstone0527** [comment] 2021-04-14 09:14
![5](https://user-images.githubusercontent.com/11675450/114685883-d746a400-9d44-11eb-922d-67d84834943f.jpg)
![6](https://user-images.githubusercontent.com/11675450/114685887-d9106780-9d44-11eb-92ac-527a45e40274.jpg)

**Comment by chrislusf** [comment] 2021-04-14 09:18
* try the dev version https://github.com/chrislusf/seaweedfs/releases/tag/dev
* Please run weed mount -cpuprofile=mount.cpu.pprof -memprofile=mount.mem.pprof to collect and share cpu and memory profiles.

Moving to qcloud? Is it cheaper?

**Comment by xstone0527** [comment] 2021-04-14 09:46
root@jp-op-admin03:~# /usr/local/seaweedfs/weed- version
version 30GB 2.39 90677e1097e18567999d98436d8c1e8eba4cc611 linux amd64

the mount command line:
root@jp-op-admin03:~# /usr/local/seaweedfs/weed- mount -cpuprofile=mount.cpu.pprof -memprofile=mount.mem.pprof -filer 10.1.180.191:8888 -dir=/seaweedfs1 >> mount.log 2>&1 &

root@jp-op-admin03:~# more mount.log 
nohup: ignoring input
This is SeaweedFS version 30GB 2.39 90677e1097e18567999d98436d8c1e8eba4cc611 linux amd64
mount point owner uid=0 gid=0 mode=drwxr-xr-x
current uid=0 gid=0
I0414 17:27:12 23529 leveldb_store.go:41] filer store dir: /tmp/82efcb6c/meta
I0414 17:27:12 23529 file_util.go:23] Folder /tmp/82efcb6c/meta Permission: -rwxr-xr-x
I0414 17:27:12 23529 mount_std.go:220] mounted 10.1.180.191:8888/ to /seaweedfs1
root@jp-op-admin03:~#

Hello,the profiles is default store dir: /tmp/82efcb6c/meta.   upload the tar file?

**Comment by chrislusf** [comment] 2021-04-14 09:56
Let "weed mount" run until the memory grows, and then `ctrl+c`. The profile is "mount.mem.pprof" should be on current directory.

**Comment by xstone0527** [comment] 2021-04-14 09:56
![7](https://user-images.githubusercontent.com/11675450/114690809-a452df00-9d49-11eb-8beb-b4c11a3b9265.jpg)

memory is not enough and the mount process state is D。the cos_migrate_tools process state is D 。moving to qcloud is not it cheap。because qcloud more stable than the current i used。 i think weed running on the iaas is a good idea

**Comment by xstone0527** [comment] 2021-04-14 10:04
[mount.mem.pprof.zip](https://github.com/chrislusf/seaweedfs/files/6310044/mount.mem.pprof.zip)

**Comment by chrislusf** [comment] 2021-04-14 10:25
can you try `weed mount -cacheCapacityMB=0 ...`?

**Comment by chrislusf** [comment] 2021-04-14 10:28
If that does not work, run "weed -v=4 mount -cacheCapacityMB=0 ..." and send the verbose logs.

**Comment by chrislusf** [comment] 2021-04-14 10:35
> [mount.mem.pprof.zip](https://github.com/chrislusf/seaweedfs/files/6310044/mount.mem.pprof.zip)

what is the file `mount.cpu.pprof`?

**Comment by xstone0527** [comment] 2021-04-14 12:32
[mount_all.zip](https://github.com/chrislusf/seaweedfs/files/6310781/mount_all.zip)

sorry,download this file,please.

**Comment by chrislusf** [comment] 2021-04-14 17:08
Seems the amount of files is the reason and I am adjusting code to adapt to that. 

Is it possible to `fs.meta.save` in `weed shell`? 

Would need it to reproduce the issue.

**Comment by xstone0527** [comment] 2021-04-15 06:51
running the fs.meta.save command ,master node cpu useage is too high.What did this command do？

**Comment by xstone0527** [comment] 2021-04-15 06:52
> fs.meta.save
total 319627 directories, 35168268 files
meta data for http://localhost:8888/ is saved to localhost-8888-20210415-154748.meta
>

**Comment by chrislusf** [comment] 2021-04-15 07:25
the meta data is saved to "localhost-8888-20210415-154748.meta". You can share the file?

**Comment by xstone0527** [comment] 2021-04-15 08:40
the meda file size is 6.4GB. is very big.

**Comment by chrislusf** [comment] 2021-04-15 09:41
Without the metadata file, I do not know how to verify the fix.

You can try the updated dev version again. https://github.com/chrislusf/seaweedfs/releases/dev

**Comment by chrislusf** [comment] 2021-04-18 21:18
2.40 has more memory fixes. Please help to verify.

**Comment by chrislusf** [comment] 2021-04-20 16:43
2.40 should have fixed it. Reopen this if not fixed.

**Closed by chrislusf** 2021-04-20 16:43 UTC
