### ISSUE TITLE
Windows: Committing vacuum error

### ISSUE THREAD

**Issue by BenBenBenny** [chrislusf/seaweedfs#1646] opened 2020-12-02 07:11 UTC
我使用了最新版，在下载了几次文件文件后，报错
命令行：
weed server -ip 192.168.1.2 -filer -filer.port=8088 -volume.index=leveldb -volume.port=9081 -volume.max=0 -dir="P:\weed\Volume2" -master.defaultReplication=000 &

使用filer功能，通过http下载
 Dim client As New WebClient
client.DownloadFile(remotefile, localfile)

日志：
I1202 14:35:54 13348 volume_layout.go:340] Volume 7 becomes unwritable
I1202 14:35:54 13348 topology_vacuum.go:70] 0 Start vacuuming 7 on 192.168.1.2:9081
I1202 14:35:54 13348 topology_vacuum.go:82] Complete vacuuming 7 on 192.168.1.2:9081
I1202 14:35:54 13348 topology_vacuum.go:106] Start Committing vacuum 7 on 192.168.1.2:9081
I1202 14:35:55 13348 volume_vacuum.go:93] Committing volume 7 vacuuming...
E1202 14:35:55 13348 volume_grpc_vacuum.go:50] commit volume 7: remove P:\weed\Volume2/7.dat: The process cannot access the file because it is being used by ano
ther process.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x18444f2]

goroutine 58 [running]:
github.com/chrislusf/seaweedfs/weed/topology.batchVacuumVolumeCommit.func1(0x249be00, 0xc00080ab60, 0xc0007dfad0, 0x3284080)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/topology/topology_vacuum.go:111 +0xb2
github.com/chrislusf/seaweedfs/weed/operation.WithVolumeServerClient.func1(0xc00074ae00, 0x11, 0xc0007dfb30)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/operation/grpc_client.go:26 +0x82
github.com/chrislusf/seaweedfs/weed/pb.WithCachedGrpcClient(0xc0007dfb40, 0xc00255ed40, 0x11, 0xc0007dfb30, 0x1, 0x1, 0xc00197c96c, 0xc0007dfba8)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/pb/grpc_client_server.go:106 +0x15b
github.com/chrislusf/seaweedfs/weed/operation.WithVolumeServerClient(0xc00197c960, 0x10, 0x2434f60, 0xc000006b08, 0xc0007dfc40, 0xc00197c958, 0x4)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/operation/grpc_client.go:24 +0x1b5
github.com/chrislusf/seaweedfs/weed/topology.batchVacuumVolumeCommit(0x2434f60, 0xc000006b08, 0xc000409490, 0xc000000007, 0xc001a84720, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/topology/topology_vacuum.go:107 +0x32b
github.com/chrislusf/seaweedfs/weed/topology.vacuumOneVolumeLayout(0x2434f60, 0xc000006b08, 0xc000409490, 0xc00053f500, 0x3fd3333333333333, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/topology/topology_vacuum.go:193 +0x4f4
github.com/chrislusf/seaweedfs/weed/topology.(*Topology).Vacuum(0xc0005978c0, 0x2434f60, 0xc000006b08, 0x3fd3333333333333, 0x0)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/topology/topology_vacuum.go:164 +0x245
github.com/chrislusf/seaweedfs/weed/topology.(*Topology).StartRefreshWritableVolumes.func2(0xc0005978c0, 0x2434f60, 0xc000006b08, 0x0, 0x3fd3333333333333)
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/topology/topology_event_handling.go:26 +0x117
created by github.com/chrislusf/seaweedfs/weed/topology.(*Topology).StartRefreshWritableVolumes
        /home/travis/gopath/src/github.com/chrislusf/seaweedfs/weed/topology/topology_event_handling.go:22 +0x96

**Comment by chrislusf** [comment] 2020-12-05 05:50
I added a possible fix for this.

I could not reproduce this. Is this always reproducible? Maybe there are some other operations?

**Closed** 2020-12-05 05:50 UTC
